'''
File for the DASH interaction side
'''

from astropy.coordinates import SkyCoord
import numpy as np
import plotly.graph_objects as go
import yaml
from astropy import units as u
from Backend.astro_objects import Galaxy, make_wcs
from Backend.generate_field import generate_field


def add_object(fig, galaxy, xs, ys, grid, cs, usename=True):
    """Overlay a galaxy and its heatmap onto an on-sky projection.

    Adds a background heatmap (e.g. a probability or intensity field) and a
    hover-enabled marker for ``galaxy`` to an existing Plotly figure, projecting
    the galaxy's sky coordinates into pixel space via the module WCS. Intended
    for rendering in a Dash app.

    Args:
        fig (plotly.graph_objects.Figure): Figure to draw on. Mutated in place.
        galaxy (Galaxy): Galaxy object from astro_objects.py. Must expose
            ``coord`` (an astropy SkyCoord), ``name``, and ``notes``.
        xs (array-like): X (pixel) coordinates for the heatmap columns.
        ys (array-like): Y (pixel) coordinates for the heatmap rows.
        grid (2D array-like): Heatmap z-values, expected normalized to [0, 1].
        cs (str or list): Plotly colorscale for the heatmap.
        usename (bool, optional): If True, draw the galaxy's name as a label
            above the marker. Defaults to True.

    Returns:
        plotly.graph_objects.Figure: The same ``fig``, with the heatmap, marker,
        and optional name label added.
    """

    wcs = make_wcs()
    px = wcs.all_world2pix([[galaxy.coord.ra.deg, galaxy.coord.dec.deg]], 0)[0]

    ra_str  = galaxy.coord.ra.to_string(unit=u.hourangle, sep=('\u02b0', '\u1d50', '\u02e2'), pad=True)
    dec_str = galaxy.coord.dec.to_string(unit=u.deg, sep=('\u00b0', '\u2032', '\u2033'), pad=True, alwayssign=True)

    fig.add_trace(go.Heatmap(
        x          = xs, 
        y          = ys, 
        z          = grid,
        zmin       = 0,
        zmax       = 1,
        colorscale = cs,
        showscale  = False,
    ))

    fig.add_trace(go.Scatter(
        x=[px[0]], y=[px[1]], mode="markers",
        marker=dict(size=6, color="rgba(0,0,0,0)"),
        name=galaxy.name,
        hovertemplate=f"RA: {ra_str}<br>Dec: {dec_str}<extra></extra>",
        customdata=[[galaxy.name, galaxy.notes]],
    ))
    
    if usename:
        fig.add_annotation(
            x=px[0], y=px[1], text=galaxy.name,
            yshift=10, showarrow=False,
            font=dict(color="white", size=10),
        )

    fig.update_layout(
        hoverlabel=dict(
            bgcolor="rgba(20, 20, 50, 0.9)",   # background color
            bordercolor="rgba(255,255,255,0.3)", # border color
            font=dict(
                color="white",
                size=13,
                family="monospace",
            ),
        )
    )

    return fig


def add_catalog_objects(fig, catalog_path, exposure_time):
    """Load a catalog file and overlay every object onto an on-sky projection.

    Reads a YAML catalog, constructs a ``Galaxy`` for each entry, and adds it to
    ``fig`` via :func:`add_object`. Each object's heatmap data is generated by
    the galaxy itself through ``prepare_figure_data``. Intended for rendering in
    a Dash app.

    Args:
        fig (plotly.graph_objects.Figure): Figure to draw on. Mutated in place.
        catalog_path (str or os.PathLike): Path to the YAML catalog. Expected to
            contain an ``objects`` key listing dicts with the fields ``ra``,
            ``dec`` (parsed as hourangle/degrees), ``redshift``, ``name``,
            ``mass_msun``, ``q``, ``type``, ``size_arcmin``, and ``notes``.
        exposure_time (float): Exposure time applied to every galaxy, in the
            units expected by ``Galaxy`` (e.g. seconds).

    Returns:
        plotly.graph_objects.Figure: The same ``fig``, with every catalog object
        drawn on it.
    """
    with open(catalog_path, "r") as f:
        catalog = yaml.safe_load(f)

    for obj in catalog["objects"]:

        coord  = SkyCoord(ra=obj["ra"], dec=obj["dec"], unit=(u.hourangle, u.deg))
        galaxy = Galaxy(
                ra            = coord.ra.to(u.deg).value,
                dec           = coord.dec.to(u.deg).value, 
                z             = float(obj["redshift"]), 
                name          = obj["name"],
                mass          = float(obj["mass_msun"]),
                q             = float(obj["q"]),
                type          = obj["type"],
                size          = float(obj["size_arcmin"]),
                notes         = obj["notes"],
                exposure_time = exposure_time,
            )

        xs, ys, grid, cs = galaxy.prepare_figure_data()
        fig = add_object(fig, galaxy, xs, ys, grid, cs, usename=True)

    return fig


def add_random_field(fig, exposure_time, seed):
    """Generate a random galaxy/cluster field and overlay it on an on-sky projection.

    Builds a procedurally generated field of galaxies and clusters covering the
    full sky and adds every galaxy to ``fig`` via :func:`add_object`. Cluster
    members are unpacked and drawn individually. Object name labels are
    suppressed, since the field is dense. Use in place of
    :func:`add_catalog_objects` when you want a synthetic field rather than a
    curated catalog.

    Args:
        fig (plotly.graph_objects.Figure): Figure to draw on. Mutated in place.
        exposure_time (float): Exposure time applied to every galaxy, in the
            units expected by ``Galaxy`` (e.g. seconds).
        seed: Seed for the field generator, for reproducible fields. Passed
            through to :func:`generate_field`.

    Returns:
        plotly.graph_objects.Figure: The same ``fig``, with the full field drawn
        on it.
    """

    field = generate_field(ra_center=180.0, dec_center=0.0, width=360.0, height=180.0, 
                           n_gals=200, n_clusters=5, seed=seed, exposure_time=exposure_time)
    
    for object in field:

        if isinstance(object, Galaxy):
            xs, ys, grid, cs = object.prepare_figure_data()
            fig = add_object(fig, object, xs, ys, grid, cs, usename=False)

        else:
            for galaxy in object.members:
                xs, ys, grid, cs = galaxy.prepare_figure_data()
                fig = add_object(fig, galaxy, xs, ys, grid, cs, usename=False)
    
    return fig



def init_graph(catalog_path, exposure_time, random_field=False, seed=None):
    """Build the base sky-chart figure and populate it with objects.

    Constructs an Aitoff-style on-sky projection: draws the coordinate graticule
    (declination parallels every 15° and RA meridians every hour, with labels),
    an outer boundary ellipse, and a dark themed layout with a 1:1 aspect ratio.
    Then overlays either a curated catalog or a procedurally generated random
    field, depending on ``random_field``. Intended as the top-level figure
    builder for a Dash app.

    Args:
        catalog_path (str or os.PathLike): Path to the YAML catalog passed to
            :func:`add_catalog_objects`. Used only when ``random_field`` is
            False, but always required by the signature — pass a placeholder (or
            see note below) when generating a random field.
        exposure_time (float): Exposure time applied to every galaxy, in the
            units expected by ``Galaxy`` (e.g. seconds).
        random_field (bool, optional): If True, populate the chart with a random
            field via :func:`add_random_field` instead of reading the catalog.
            Defaults to False.
        seed (int or None, optional): Seed forwarded to :func:`add_random_field`
            for reproducibility. Only used when ``random_field`` is True.
            Defaults to None.

    Returns:
        plotly.graph_objects.Figure: A fully assembled figure with graticule,
        boundary, and overlaid objects, ready to hand to Dash.
    """
    wcs        = make_wcs()
    n_pts      = 400
    grid_color = "rgba(255,255,255,0.15)"
    label_color= "rgba(255,255,255,0.55)"
    traces     = []

    # ── Dec parallels (sweeps through RA) ──────────────────────────
    ra_sweep = np.linspace(0.5, 359.5, n_pts)
    for dec in range(-90, 91, 15):
        sky = np.column_stack([ra_sweep, np.full(n_pts, float(dec))])
        px  = wcs.all_world2pix(sky, 0)
        traces.append(go.Scatter(
            x=px[:, 0], y=px[:, 1],
            mode="lines",
            line=dict(color=grid_color, width=0.8),
            hoverinfo="skip",
            showlegend=False,
        ))
        # Label on the central meridian (RA = 180)
        lx, ly = wcs.all_world2pix([[180, dec]], 0)[0]
        traces.append(go.Scatter(
            x=[lx + 3], y=[ly],
            mode="text",
            text=[f"{dec:+d}°"],
            textfont=dict(color=label_color, size=9),
            hoverinfo="skip",
            showlegend=False,
        ))

    # ── RA meridians (sweeps through Dec) ─────────────────────────
    dec_sweep = np.linspace(-89.9, 89.9, n_pts)
    for ra_h in range(0, 24):
        ra_deg = ra_h * 15.0
        sky = np.column_stack([np.full(n_pts, ra_deg), dec_sweep])
        px  = wcs.all_world2pix(sky, 0)
        traces.append(go.Scatter(
            x=px[:, 0], y=px[:, 1],
            mode="lines",
            line=dict(color=grid_color, width=0.8),
            hoverinfo="skip",
            showlegend=False,
        ))
        # Label along the equator (Dec = 0)
        lx, ly = wcs.all_world2pix([[ra_deg, 0]], 0)[0]
        traces.append(go.Scatter(
            x=[lx], y=[ly - 6],
            mode="text",
            text=[f"{ra_h}h"],
            textfont=dict(color=label_color, size=9),
            hoverinfo="skip",
            showlegend=False,
        ))

    # ── Outer boundary ellipse ────────────────────────────────────────────────
    theta = np.linspace(0, 2 * np.pi, 500)
    # boundary in WCS pixel coords
    bx = 163.0 * np.cos(theta)
    by =  82.0 * np.sin(theta)
    traces.append(go.Scatter(
        x=bx, y=by,
        mode="lines",
        line=dict(color="rgba(255,255,255,0.35)", width=1.2),
        hoverinfo="skip",
        showlegend=False,
    ))

    fig = go.Figure(data=traces)
    fig.update_layout(
        paper_bgcolor="#222222",
        plot_bgcolor="#222222",
        margin=dict(l=20, r=20, t=20, b=20),
        xaxis=dict(
            visible=False,
            range=[-175, 175],
            scaleanchor="y",
            scaleratio=1,
        ),
        yaxis=dict(
            visible=False,
            range=[-95, 95],
        ),
        showlegend=False,
        dragmode="pan",
    )


    # Now add objects
    if random_field:
        fig = add_random_field(fig, exposure_time=exposure_time, seed=seed)
    else:
        fig = add_catalog_objects(fig, catalog_path=catalog_path, exposure_time=exposure_time)

    return fig
